-- Do *NOT* forget to change all $DIRECTORY_DATA$ and $DIRECTORY_INDEX$
--   by the actual directory, e.g.: 
-- FILE="oracle-users.sql"; sed -e 's/\$DIRECTORY_DATA\$/\/u01\/app\/oracle\/oradata\/orcl/g' -e 's/\$DIRECTORY_INDEX\$/\/u01\/app\/oracle\/oradata\/orcl/g' -e 's/"TEMPORARY"/"TEMP"/g' ${FILE} > ${FILE}.new; diff ${FILE} ${FILE}.new
-- echo "QUIT;" | sqlplus system/password @ ${FILE}.new
--
-- To drop all users:
--   { for USER in DEV TST PRD; do echo "DROP USER \"RUBY${USER}\" CASCADE;"; done } | sqlplus system/password;
-- To drop all tables:
--   { for TS in DEV TST PRD; do echo -e "DROP TABLESPACE \"SAMPLE_APP_${TS}\"\n/\nDROP TABLESPACE \"SAMPLE_APP_${TS}_INDEX\"\n/\n"; done } | sqlplus system/password
--
--
--
-- development
-- user: RUBYDEV
-- pass: RUBYDEV
-- schema: SAMPLE_APP_DEV
CREATE TABLESPACE "SAMPLE_APP_DEV"
    LOGGING
    DATAFILE '$DIRECTORY_DATA$/SAMPLE_DATA_DEV.dbf' SIZE 100M
    REUSE EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO
/
CREATE TABLESPACE "SAMPLE_APP_DEV_INDEX"
    LOGGING
    DATAFILE '$DIRECTORY_INDEX$/SAMPLE_DATA_DEV_INDEX.dbf' SIZE 20M
    REUSE EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO
/
CREATE USER "RUBYDEV"  PROFILE "DEFAULT"
    IDENTIFIED BY RUBYDEV DEFAULT TABLESPACE "SAMPLE_APP_DEV"
    TEMPORARY TABLESPACE "TEMP"
    QUOTA UNLIMITED
    ON "SAMPLE_APP_DEV"
    QUOTA UNLIMITED
    ON "SAMPLE_APP_DEV_INDEX"
    ACCOUNT UNLOCK
/
GRANT CONNECT TO "RUBYDEV"
/
GRANT RESOURCE TO "RUBYDEV"
/
GRANT CREATE TABLE TO "RUBYDEV"
/
GRANT CREATE SEQUENCE TO "RUBYDEV"
/
REVOKE UNLIMITED TABLESPACE FROM "RUBYDEV"
/
-- test
-- user: RUBYTST
-- pass: RUBYTST
-- schema: SAMPLE_APP_TST
CREATE TABLESPACE "SAMPLE_APP_TST"
    LOGGING
    DATAFILE '$DIRECTORY_DATA$/SAMPLE_DATA_TST.dbf' SIZE 100M
    REUSE EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO
/
CREATE TABLESPACE "SAMPLE_APP_TST_INDEX"
    LOGGING
    DATAFILE '$DIRECTORY_INDEX$/SAMPLE_DATA_TST_INDEX.dbf' SIZE 20M
    REUSE EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO
/
CREATE USER "RUBYTST"  PROFILE "DEFAULT"
    IDENTIFIED BY RUBYTST DEFAULT TABLESPACE "SAMPLE_APP_TST"
    TEMPORARY TABLESPACE "TEMP"
    QUOTA UNLIMITED
    ON "SAMPLE_APP_TST"
    QUOTA UNLIMITED
    ON "SAMPLE_APP_TST_INDEX"
    ACCOUNT UNLOCK
/
GRANT CONNECT TO "RUBYTST"
/
GRANT RESOURCE TO "RUBYTST"
/
GRANT CREATE TABLE TO "RUBYTST"
/
GRANT CREATE SEQUENCE TO "RUBYTST"
/
REVOKE UNLIMITED TABLESPACE FROM "RUBYTST"
/
-- production
-- user: RUBYPRD
-- pass: RUBYPRD
-- schema: SAMPLE_APP_PRD
CREATE TABLESPACE "SAMPLE_APP_PRD"
    LOGGING
    DATAFILE '$DIRECTORY_DATA$/SAMPLE_DATA_PRD.dbf' SIZE 100M
    REUSE EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO
/
CREATE TABLESPACE "SAMPLE_APP_PRD_INDEX"
    LOGGING
    DATAFILE '$DIRECTORY_INDEX$/SAMPLE_DATA_PRD_INDEX.dbf' SIZE 20M
    REUSE EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO
/
CREATE USER "RUBYPRD"  PROFILE "DEFAULT"
    IDENTIFIED BY RUBYPRD DEFAULT TABLESPACE "SAMPLE_APP_PRD"
    TEMPORARY TABLESPACE "TEMP"
    QUOTA UNLIMITED
    ON "SAMPLE_APP_PRD"
    QUOTA UNLIMITED
    ON "SAMPLE_APP_PRD_INDEX"
    ACCOUNT UNLOCK
/
GRANT CONNECT TO "RUBYPRD"
/
GRANT RESOURCE TO "RUBYPRD"
/
GRANT CREATE TABLE TO "RUBYPRD"
/
GRANT CREATE SEQUENCE TO "RUBYPRD"
/
REVOKE UNLIMITED TABLESPACE FROM "RUBYPRD"
/
-- quota
ALTER USER "RUBYDEV" QUOTA 100M ON "SAMPLE_APP_DEV"
/
ALTER USER "RUBYTST" QUOTA 100M ON "SAMPLE_APP_TST"
/
ALTER USER "RUBYPRD" QUOTA 100M ON "SAMPLE_APP_PRD"
/
