development:
    adapter: oracle_enhanced
    username: rubydev
    password: rubydev
    database: localhost/orcl

test:
    adapter: oracle_enhanced
    username: rubytst
    password: rubytst
    database: localhost/orcl

production:
    adapter: oracle_enhanced
    username: rubyprd
    password: rubyprd
    database: localhost/orcl

cucumber:
  <<: *test
