development:
  adapter: mysql2
  encoding: utf8
  database: sampleapp_dev
  username: rubydev
  password: rubydev
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: sampleapp_tst
  username: rubytst
  password: rubytst
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: sampleapp_prd
  username: rubyprd
  password: rubyprd
  host: 127.0.0.1
  port: 3306

cucumber:
  adapter: mysql2
  encoding: utf8
  database: sampleapp_tst
  username: rubytst
  password: rubytst
  host: 127.0.0.1
  port: 3306

