development:
    adapter: oracle_enhanced
    username: rubydev
    password: rubydev

test:
    adapter: oracle_enhanced
    username: rubytst
    password: rubytst

production:
    adapter: oracle_enhanced
    username: rubyprd
    password: rubyprd

cucumber:
    adapter: oracle_enhanced
    username: rubytst
    password: rubytst
